import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-100 to-yellow-50`}
      >
        {children}
      </body>
    </html>
  );
}
