import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/sessionProvider/authProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-100 to-yellow-50`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
